services:
  ml-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: credit-card-ml-service
    ports:
      - "5000:5000"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8081:80"
    depends_on:
      - ml-service